- name: Add Prometheus repository for CentOS
  yum_repository:
    name: prometheus
    description: Prometheus repository
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
    gpgcheck: 1
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
    enabled: 1
  when: ansible_distribution == "CentOS"

- name: Import GPG key for Prometheus
  rpm_key:
    key: https://packagecloud.io/prometheus-rpm/release/gpgkey
  when: ansible_distribution == "CentOS"

- name: Install Prometheus
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Prometheus
  yum:
    name: prometheus
    state: present
  when: ansible_distribution == "CentOS"

- name: Install necessary packages for Prometheus
  apt:
    name: 
      - prometheus-node-exporter
      - prometheus-alertmanager
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install necessary packages for Prometheus
  yum:
    name: 
      - prometheus-node-exporter
      - prometheus-alertmanager
    state: present
  when: ansible_distribution == "CentOS"
