- name: Install Prometheus and Requirements
  hosts: all
  become: true
  tasks:
    - name: Install required packages for Prometheus
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - prometheus
        - prometheus-node-exporter
      when: ansible_distribution == "Ubuntu"

    - name: Install required packages for Prometheus
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - prometheus
        - prometheus-node-exporter
      when: ansible_distribution == "CentOS"
