- name: Install Prometheus
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install Prometheus
  yum:
    name: prometheus
    state: present
  when: ansible_distribution == "CentOS"

- name: Install necessary packages for Prometheus
  apt:
    name: 
      - prometheus-node-exporter
      - prometheus-alertmanager
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install necessary packages for Prometheus
  yum:
    name: 
      - prometheus-node-exporter
      - prometheus-alertmanager
    state: present
  when: ansible_distribution == "CentOS"
